### ISSUE TITLE
Python Code

### ISSUE THREAD

**Issue by phathulkp** [Ahyaya/statNS#1]
Can u help me in writing a python code for f mode frequency in this manner. I have been trying to solve it but am at present confused at a point. Why does it print for 1.4 Solar mass instead of 2.2 Solar mass
thanks

**Comment by Ahyaya** [comment]
You may change the desired mass setting at line 46, an example use would be like that
myRhoc = statNS.M2Rhoc(pointer(myEoS), 2.2)
statNS.solveTOV(Results,pointer(myEoS),myRhoc)
print("M=", Results[0].M, "R=", Results[0].r, "I=", Results[0].I, "Lambda=", Results[0].Lambda)

I'm new in writing python code, but I can make it work.
You may contact me through email for any further discussion, better post your question with scripts or snapshots.

my email: c.houyuan@mail.scut.edu.cn
